# Generated by Django 5.0.4 on 2024-10-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lock',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
