# Generated by Django 5.0.4 on 2024-10-09 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_user_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='Banners')),
                ('logo', models.ImageField(upload_to='logos')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_description', models.TextField()),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_icon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
