# Generated by Django 5.0.4 on 2024-10-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
