# Generated by Django 5.0.4 on 2024-10-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0004_shops_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
