# Generated by Django 5.0.4 on 2024-10-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0005_shops_latitude_shops_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='brn',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='tin',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='validids',
            field=models.ImageField(default=1, upload_to='valid_id', verbose_name='Owners valid id'),
            preserve_default=False,
        ),
    ]
