# Generated by Django 5.0.4 on 2024-10-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0006_shops_brn_shops_tin_shops_validids'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='status',
            field=models.CharField(default='lock', max_length=50),
        ),
    ]
