# Generated by Django 5.0.4 on 2024-10-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0009_alter_shops_owner_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vehicle',
        ),
    ]
