# Generated by Django 5.0.4 on 2024-10-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0011_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='vehicle',
        ),
    ]
