# Generated by Django 5.0.4 on 2024-10-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0013_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
