# Generated by Django 5.0.4 on 2024-10-11 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0015_vehicle_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='img5',
        ),
    ]
