# Generated by Django 5.0.4 on 2024-10-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0016_remove_vehicle_img2_remove_vehicle_img3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='seat',
            field=models.IntegerField(choices=[(2, '2 Seater'), (4, '4 Seater'), (5, '5 Seater'), (6, '6 Seater'), (8, '8 Seater')]),
        ),
    ]
