# Generated by Django 5.0.4 on 2024-10-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0017_alter_vehicle_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='img2',
            field=models.ImageField(default=1, upload_to='Vehicle Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img3',
            field=models.ImageField(default=1, upload_to='Vehicle Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img4',
            field=models.ImageField(default=1, upload_to='Vehicle Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img5',
            field=models.ImageField(default=1, upload_to='Vehicle Image'),
            preserve_default=False,
        ),
    ]
