# Generated by Django 5.0.4 on 2024-10-11 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0018_vehicle_img2_vehicle_img3_vehicle_img4_vehicle_img5'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vehicle',
        ),
    ]
