# Generated by Django 5.0.4 on 2024-10-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0020_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='documents',
            field=models.FileField(default=1, upload_to='Car Documents'),
            preserve_default=False,
        ),
    ]
