# Generated by Django 5.0.4 on 2024-10-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0021_vehicle_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
