# Generated by Django 5.0.4 on 2024-10-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0025_rename_phone_number_driver_phone_number1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='driver',
        ),
    ]
