# Generated by Django 5.0.4 on 2024-10-15 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0026_delete_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivers_license', models.ImageField(upload_to='Drivers License')),
                ('phone_number', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_driver', to=settings.AUTH_USER_MODEL, verbose_name='Account Driver')),
                ('shop_under', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopdriver', to='transportation.shops', verbose_name='Shop Driver')),
            ],
        ),
    ]
