# Generated by Django 5.0.4 on 2024-10-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0027_driver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='driver',
            new_name='driver_shop',
        ),
    ]
