# Generated by Django 5.0.4 on 2024-10-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0028_rename_driver_driver_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_shop',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
