# Generated by Django 5.0.4 on 2024-10-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0030_driver_shop_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rent_per_hr',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
