# Generated by Django 5.0.4 on 2024-10-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0031_vehicle_rent_per_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='rent_per_hr',
            field=models.IntegerField(),
        ),
    ]
