# Generated by Django 5.0.4 on 2024-10-23 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0032_alter_vehicle_rent_per_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_shop',
            name='drivers_rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rented_Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_unit', models.DateTimeField()),
                ('return_unit', models.DateTimeField()),
                ('total_fare', models.IntegerField(default=88)),
                ('status', models.CharField(default='unpaid', max_length=50)),
                ('driver_shp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driversinrent', to='transportation.driver_shop', verbose_name='Driver')),
                ('renters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renters_driver', to=settings.AUTH_USER_MODEL, verbose_name='renters')),
                ('unit_rented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitrented', to='transportation.vehicle', verbose_name='Unit Rented')),
            ],
        ),
    ]
