# Generated by Django 5.0.4 on 2024-10-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0033_driver_shop_drivers_rate_rented_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='total_hrs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
