# Generated by Django 5.0.4 on 2024-10-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0035_alter_driver_shop_drivers_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='renter_validid',
            field=models.ImageField(default=1, upload_to='RentersID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rented_cars',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
