# Generated by Django 5.0.4 on 2024-10-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0036_rented_cars_renter_validid_alter_rented_cars_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented_cars',
            name='renter_validid',
            field=models.FileField(upload_to='RentersID', verbose_name='Your 2 Valid(s) in 1 PDF'),
        ),
    ]
