# Generated by Django 5.0.4 on 2024-10-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0038_controls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controls',
            options={'verbose_name': 'controls', 'verbose_name_plural': 'controls'},
        ),
    ]
