# Generated by Django 5.0.4 on 2024-10-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0039_alter_controls_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='controls',
            name='site',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
