# Generated by Django 5.0.4 on 2024-11-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0041_alter_controls_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controls',
            name='control',
            field=models.IntegerField(choices=[(1, 'Lock'), (2, 'Unclock')]),
        ),
    ]
