# Generated by Django 5.0.4 on 2024-11-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0042_alter_controls_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='drivers_approval',
            field=models.IntegerField(default=0),
        ),
    ]
