# Generated by Django 5.0.4 on 2024-11-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0044_alter_rented_cars_drivers_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='car_fee_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rented_cars',
            name='driver_fee_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
