# Generated by Django 5.0.4 on 2024-11-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0046_rented_cars_payment_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='rent_id',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True, verbose_name='RENTID'),
            preserve_default=False,
        ),
    ]
