# Generated by Django 5.0.4 on 2024-11-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0047_rented_cars_rent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rented_cars',
            name='rent_id',
        ),
    ]
