# Generated by Django 5.0.4 on 2024-11-19 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0049_rented_cars_rent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='onsitepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('date_pay', models.DateTimeField(auto_now=True)),
                ('proof_resibo', models.ImageField(upload_to='Reciepts')),
                ('rent_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.rented_cars', verbose_name='rent payment')),
            ],
            options={
                'verbose_name': 'onsitepayment',
                'verbose_name_plural': 'onsitepayments',
            },
        ),
    ]
