# Generated by Django 5.0.4 on 2024-11-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0050_onsitepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='unit_release',
            field=models.CharField(choices=[(1, 'Garage'), (2, 'Road')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
