# Generated by Django 5.0.4 on 2024-11-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0051_rented_cars_unit_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented_cars',
            name='unit_release',
            field=models.CharField(choices=[(1, 'Garage'), (2, 'Road')], default=1, max_length=50),
        ),
    ]
