# Generated by Django 5.0.4 on 2024-11-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0052_alter_rented_cars_unit_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rented_cars',
            name='unit_release',
        ),
        migrations.AddField(
            model_name='rented_cars',
            name='unit_releases',
            field=models.IntegerField(choices=[(1, 'Garage'), (2, 'Road')], default=1),
        ),
        migrations.AlterField(
            model_name='onsitepayment',
            name='rent_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='transportation.rented_cars', verbose_name='rent payment'),
        ),
    ]
