# Generated by Django 5.0.4 on 2024-11-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0053_remove_rented_cars_unit_release_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rented_cars',
            old_name='unit_releases',
            new_name='unit_release',
        ),
    ]
