# Generated by Django 5.0.4 on 2024-11-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0054_rename_unit_releases_rented_cars_unit_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='out_garage',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
