# Generated by Django 5.0.4 on 2024-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0056_alter_rented_cars_out_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='return_garage',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
