# Generated by Django 5.0.4 on 2024-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0057_rented_cars_return_garage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented_cars',
            name='return_garage',
            field=models.DateTimeField(),
        ),
    ]
