# Generated by Django 5.0.4 on 2024-11-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0058_alter_rented_cars_return_garage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented_cars',
            name='out_garage',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rented_cars',
            name='return_garage',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rented_cars',
            name='unit_release',
            field=models.IntegerField(choices=[(1, 'Inside Garage'), (2, 'Road'), (3, 'Return Garage')], default=1),
        ),
    ]
