# Generated by Django 5.0.4 on 2024-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0059_alter_rented_cars_out_garage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='transaction_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rented_cars',
            name='unit_release',
            field=models.IntegerField(choices=[(1, 'Inside Garage'), (2, 'Outside'), (3, 'Return Garage')], default=1),
        ),
    ]
