# Generated by Django 5.0.4 on 2024-11-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0060_rented_cars_transaction_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='execes_hrs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rented_cars',
            name='paid_excess',
            field=models.IntegerField(default=0),
        ),
    ]
