# Generated by Django 5.0.4 on 2024-11-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0062_rented_cars_execes_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='excess_exist',
            field=models.IntegerField(default=0),
        ),
    ]
