# Generated by Django 5.0.4 on 2024-11-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0063_rented_cars_excess_exist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented_cars',
            name='execes_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rented_cars',
            name='execes_hrs',
            field=models.IntegerField(null=True),
        ),
    ]
