# Generated by Django 5.0.4 on 2024-12-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0065_rented_cars_mth_rented_cars_sqc_rented_cars_yr'),
    ]

    operations = [
        migrations.CreateModel(
            name='rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rates', models.IntegerField()),
            ],
            options={
                'verbose_name': 'rates',
                'verbose_name_plural': 'rates',
            },
        ),
    ]
