# Generated by Django 5.0.4 on 2024-12-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0066_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='liquidated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rented_cars',
            name='share_rates',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
