# Generated by Django 5.0.4 on 2024-12-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0069_payment_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_process',
            name='date_submitted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
