# Generated by Django 5.0.4 on 2024-12-01 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0070_payment_process_date_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_process_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.payment_process', verbose_name='root')),
                ('rent_transactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.rented_cars', verbose_name='renttransaction')),
            ],
        ),
    ]
