# Generated by Django 5.0.4 on 2024-12-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0072_alter_onsitepayment_rent_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='rating_bolean',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rented_cars',
            name='rating_reviews',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rented_cars',
            name='rating_star',
            field=models.IntegerField(default=0),
        ),
    ]
