# Generated by Django 5.0.4 on 2024-12-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0073_rented_cars_rating_bolean_rented_cars_rating_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented_cars',
            name='rating_star',
            field=models.IntegerField(choices=[(1, 'one star'), (2, 'two star'), (3, 'three star'), (4, 'four star'), (5, 'five star')], default=0),
        ),
    ]
