# Generated by Django 5.0 on 2025-03-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0074_alter_rented_cars_rating_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='issues',
            field=models.IntegerField(default=0),
        ),
    ]
