# Generated by Django 5.0 on 2025-04-01 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0075_rented_cars_issues'),
    ]

    operations = [
        migrations.CreateModel(
            name='rent_issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_details', models.TextField()),
                ('issue_amount', models.IntegerField(default=500)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.rented_cars', verbose_name='Rent cars issue')),
            ],
        ),
    ]
