# Generated by Django 5.0 on 2025-04-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0076_rent_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_issue',
            name='issue_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
