# Generated by Django 5.0 on 2025-04-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0077_rent_issue_issue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_cars',
            name='total_cost_issue',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
