# Generated by Django 5.0 on 2025-04-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0078_rented_cars_total_cost_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented_cars',
            name='total_cost_issue',
            field=models.IntegerField(default=0),
        ),
    ]
